using System.Text.RegularExpressions;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
using StardewModdingAPI;
using StardewValley;

namespace OldFarmer;

/// <summary>
/// Draws the SAN (Sanity) bar on the HUD, using a copy of the vanilla
/// stamina-bar container sprite with its "E" (Energy) glyph replaced by an
/// "S" (Sanity) glyph (see <c>tools/san_bar.lua</c>), plus the vanilla fill
/// formula (0.625 height scale).
///
/// All math is a 1:1 clone of Game1.drawHUD's stamina section, with
/// maxSan replacing player.MaxStamina and _displayedSan replacing player.Stamina.
/// </summary>
internal static class SanBarDrawer
{
    // ── SAN-bar sprite (vanilla stamina bar copied, "E" → "S") ────
    //    assets/sprites/san_bar.png is 12×48: three 12×16 tiles stacked
    //    (top cap / middle stretch / bottom cap), generated by tools/san_bar.lua.
    private static Texture2D? _barTexture;

    private static readonly Rectangle SrcTop    = new(0,  0, 12, 16);
    private static readonly Rectangle SrcMiddle = new(0, 16, 12, 16);
    private static readonly Rectangle SrcBottom = new(0, 32, 12, 16);

    /// <summary>Loads the SAN-bar texture. Call once from <c>ModEntry.Entry</c>.</summary>
    public static void Load(IModHelper helper)
    {
        _barTexture = helper.ModContent.Load<Texture2D>("assets/sprites/san_bar.png");
    }

    private const float BarScale = 4f;   // 12 × 4 = 48 px rendered width
    private const int   BarWidth = 48;

    // ── animation state ──────────────────────────────────────────
    private static int   _shakeTimer;
    private static float _displayedSan = 100f;

    // ── vanilla HUD tooltip capture (only while the SAN bar is shown) ──
    //    While vanilla draws the HUD status bars, its numeric health/stamina
    //    readouts are captured and suppressed (see HudTooltipPatches) so they
    //    can be redrawn at the SAN bar's top-left corner instead.
    private static bool _inVanillaHud;
    private static readonly List<(string Text, Color Color)> _vanillaTooltips = new();
    private static readonly Regex NumericTooltip = new(@"^\d+/\d+$", RegexOptions.Compiled);

    public static void BeginVanillaHud()
    {
        _vanillaTooltips.Clear();
        _inVanillaHud = true;
    }

    public static void EndVanillaHud() => _inVanillaHud = false;

    /// <summary>
    /// Called from the <c>drawWithBorder</c> Harmony patch. Captures vanilla's
    /// numeric health/stamina readout while the SAN bar is visible so it can be
    /// redrawn beside the SAN bar. Returns true when the original draw should
    /// be suppressed.
    /// </summary>
    public static bool TryCaptureTooltip(string message, Color insideColor)
    {
        if (!_inVanillaHud || !ShouldDraw)
            return false;
        if (!NumericTooltip.IsMatch(message))
            return false;
        // Vanilla draws the stamina readout in white and the health readout in
        // red; require one of those so unrelated "n/m" text is never swallowed.
        if (insideColor != Color.White && insideColor != Color.Red)
            return false;

        _vanillaTooltips.Add((message, insideColor));
        return true;
    }

    /// <summary>
    /// Set to false when grandpa fades out (SAN = 0).
    /// The SAN bar will be hidden until the next grandpa spawn.
    /// </summary>
    public static bool ShouldDraw { get; set; } = false; // 默认不显示，召唤后才显示

    public static void Update(float realSan)
    {
        if (_shakeTimer > 0)
            _shakeTimer -= Game1.currentGameTime.ElapsedGameTime.Milliseconds;

        float delta = realSan - _displayedSan;
        _displayedSan += delta * 0.15f;
        if (Math.Abs(delta) < 0.1f)
            _displayedSan = realSan;

        if (realSan < 20f && _shakeTimer <= 0 && Game1.random.NextDouble() < 0.01)
            _shakeTimer = 500;
    }

    public static void Draw(SpriteBatch sb, Farmer player)
    {
        if (!ShouldDraw || _barTexture == null) return;
        if (Game1.eventUp || Game1.farmEvent != null)
            return;
        if (!Context.IsWorldReady)
            return;

        var safeArea = Game1.graphics.GraphicsDevice.Viewport.TitleSafeArea;
        int   maxSan = SanManager.GetMaxSan(player);
        float num    = 2.5f;   // 0.625 × 4 = taller bar

        // ── bar height is fixed (based on 100 SAN) regardless of dynamic max ──
        const float FixedBarSan = 100f;
        float barInnerH = FixedBarSan * num;

        // ── replicate stamina bar X (Game1.drawHUD) ──
        float staminaX = safeArea.Right - 48 - 8;
        if (Game1.isOutdoorMapSmallerThanViewport())
            staminaX = Math.Min(staminaX,
                -Game1.viewport.X + Game1.currentLocation.map.Layers[0].LayerWidth * 64 - 48);

        // ── SAN bar sits 56 px left of stamina (or 112 if health bar visible) ──
        bool healthShowing = Game1.showingHealth;
        float sanX = healthShowing
            ? staminaX - 56 - 56
            : staminaX - 56;

        // ── SAN bar Y: based on fixed bar height ──
        float sanY = safeArea.Bottom - 80 - barInnerH;

        var sanVec = new Vector2(sanX, sanY);
        sanVec.Y = Math.Max(0, sanVec.Y);

        if (_shakeTimer > 0)
        {
            sanVec.X += Game1.random.Next(-3, 4);
            sanVec.Y += Game1.random.Next(-3, 4);
        }

        Color containerTint = new Color(200, 170, 255);

        // ── container: top cap (scale 4×) ──
        sb.Draw(_barTexture, sanVec,
            SrcTop, containerTint, 0f, Vector2.Zero, BarScale, SpriteEffects.None, 1f);

        // ── container: middle stretch (top cap end → just past bottom cap start) ──
        sb.Draw(_barTexture,
            new Rectangle(
                (int)sanVec.X,
                (int)(sanVec.Y + 64f),
                BarWidth,
                (int)(barInnerH - 56f)),
            SrcMiddle, containerTint);

        // ── container: bottom cap (overlaps with fill end, like vanilla) ──
        sb.Draw(_barTexture,
            new Vector2(sanVec.X, sanVec.Y + barInnerH),
            SrcBottom, containerTint, 0f, Vector2.Zero, BarScale, SpriteEffects.None, 1f);

        // ── fill — scaled so it reaches the bottom cap at full SAN ──
        //   total distance from fill start (Y+48) to bottom edge = barInnerH + 16
        int   fillMaxH  = (int)(barInnerH + 8f);
        int   fillH     = (int)(Math.Clamp(_displayedSan / maxSan, 0f, 1f) * fillMaxH);
        if (fillH < 0) fillH = 0;

        var fillRect = new Rectangle(
            (int)sanVec.X + 12,
            (int)sanVec.Y + 48 + fillMaxH - fillH,
            24,
            fillH);

        if (fillRect.Height > 0)
        {
            float ratio = Math.Clamp(_displayedSan / maxSan, 0f, 1f);
            Color fillColor = GetSanColor(ratio);

            sb.Draw(Game1.staminaRect, fillRect, fillColor);

            // Dark sheen at top of fill (vanilla trick: height=4, darker colour)
            var sheenRect = fillRect;
            sheenRect.Height = 4;
            Color sheenColor = new Color(
                Math.Max(0, fillColor.R - 50),
                Math.Max(0, fillColor.G - 50),
                Math.Max(0, fillColor.B - 40));
            sb.Draw(Game1.staminaRect, sheenRect, sheenColor);
        }

        // ── critically low pulsing icon ──
        if (_displayedSan < 20f)
        {
            float pulse = 0.75f + 0.25f * (float)Math.Sin(
                Game1.currentGameTime.TotalGameTime.TotalMilliseconds / (_displayedSan * 50f + 1f));
            sb.Draw(Game1.mouseCursors,
                sanVec - new Vector2(0f, 11f) * 4f,
                new Rectangle(191, 406, 12, 11),
                Color.MediumPurple * pulse,
                0f, Vector2.Zero, BarScale, SpriteEffects.None, 1f);
        }

        // ── unified hover tooltip ────────────────────────────────────
        //   Like vanilla (which stacks health + stamina readouts beside the
        //   left-most visible bar), every readout is drawn at the SAN bar's
        //   top-left corner while the SAN bar is visible. Vanilla's own
        //   health/stamina readouts were captured in TryCaptureTooltip.
        int mouseX = Game1.getOldMouseX();
        int mouseY = Game1.getOldMouseY();
        bool mouseOnSan = mouseX >= sanVec.X && mouseX < sanVec.X + BarWidth
                          && mouseY >= sanVec.Y && mouseY < sanVec.Y + barInnerH;

        string? tipText  = null;
        Color   tipColor = Color.White;

        if (mouseOnSan)
        {
            tipText  = $"{(int)Math.Max(0f, _displayedSan)}/{maxSan}";
            tipColor = new Color(200, 170, 255);
        }
        else if (_vanillaTooltips.Count > 0)
        {
            (tipText, tipColor) = _vanillaTooltips[0];
        }

        if (tipText != null)
        {
            Game1.drawWithBorder(
                tipText,
                Color.Black * 0f,
                tipColor,
                sanVec + new Vector2(-Game1.dialogueFont.MeasureString("999/999").X - 16f, 64f));
        }
    }

    // ── colour ramp ──────────────────────────────────────────────

    /// <summary>
    /// Maps SAN ratio [0,1] to a colour:
    ///   1.0 → bright cyan-blue  (perfectly sane)
    ///   0.5 → medium purple
    ///   0.0 → dark red-purple   (on the edge of madness)
    /// </summary>
    private static Color GetSanColor(float ratio)
    {
        // Two-segment lerp:
        //   [0.5, 1.0] → purple (#9B59B6) → cyan-blue (#5DADE2)
        //   [0.0, 0.5] → dark red-purple (#6C0F0F) → purple (#9B59B6)
        if (ratio >= 0.5f)
        {
            float t = (ratio - 0.5f) * 2f;   // 0→1 within upper half
            return Color.Lerp(
                new Color(155,  89, 182),  // mid purple
                new Color( 93, 173, 226),  // sane blue
                t);
        }
        else
        {
            float t = ratio * 2f;              // 0→1 within lower half
            return Color.Lerp(
                new Color(108,  15,  15),  // madness red-purple
                new Color(155,  89, 182),  // mid purple
                t);
        }
    }
}
